default: &default 
    abiquo_api_url: https://wf.bcn.abiquo.com/api
    abiquo_username: admin
    abiquo_password: xabiquo
    connection_options:
        ssl:
            verify: false

development: 
    <<: *default

test:
    <<: *default

production:
    <<: *default
