default: &default 
    default_action: CANCEL
    approval_role: ENTERPRISE_ADMIN

    mail_from: some_address@test.com
    approval_subject: You have a pending task pending for approval

    requester_subject: A pending task has been updated

    approval_task_types:
        - DEPLOY
        - UNDEPLOY
        - RECONFIGURE

    email_render_links: true

    smtp_settings:
        email_link_host: localhost
        email_link_port: 3000
        email_link_protocol: http
        email_link_path: /workflow
        port: 587
        address: smtp.mailgun.org
        domain: sandbox.mailgun.org
        user_name: postmaster@sandbox.mailgun.org
        password: somepassword
        authentication: :plain

development:
    <<: *default

test:
    <<: *default

production:
    <<: *default
